spool createprofilenewlog;

select name from v$database

--Creating profile with all values as unlimited

CREATE PROFILE "&PROFILE NAME" LIMIT
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME UNLIMITED
IDLE_TIME UNLIMITED
SESSIONS_PER_USER &VALUE1
LOGICAL_READS_PER_SESSION &VALUE2
LOGICAL_READS_PER_CALL &VALUE3
PRIVATE_SGA UNLIMITED
COMPOSITE_LIMIT UNLIMITED
PASSWORD_LIFE_TIME &VALUE4
PASSWORD_GRACE_TIME DEFAULT
PASSWORD_REUSE_MAX &VALUE5
PASSWORD_REUSE_TIME &VALUE6
PASSWORD_LOCK_TIME 1
FAILED_LOGIN_ATTEMPTS 10
PASSWORD_VERIFY_FUNCTION VERIFY_FUNCTION_11G


spool off;

exit;