Invoke-Expression F:\Automation\diskspace\Dev_Servers_Scripts\Dev.PS1
Invoke-Expression F:\Automation\diskspace\Test_Servers_Scripts\Test.PS1
Invoke-Expression F:\Automation\diskspace\DR_Servers_Scripts\DR.PS1
Invoke-Expression F:\Automation\diskspace\Prod_Servers_Scripts\Prod_Silver.PS1
Invoke-Expression F:\Automation\diskspace\Prod_Servers_Scripts\Prod_Gold.PS1
Invoke-Expression F:\Automation\diskspace\Prod_Servers_Scripts\Prod_Bronze.PS1